const keycodes: {
  code: string;
  keyCode: number;
  key: string;
  location: string;
}[] = [
  { code: 'NumLock', keyCode: 12, key: 'Clear', location: '0 (General keys)' },
  { code: 'NumpadDivide', keyCode: 111, key: '/', location: '3 (Numpad)' },
  { code: 'NumpadMultiply', keyCode: 106, key: '*', location: '3 (Numpad)' },
  { code: 'NumpadSubtract', keyCode: 109, key: '-', location: '3 (Numpad)' },
  { code: 'NumpadAdd', keyCode: 107, key: '+', location: '3 (Numpad)' },
  { code: 'NumpadEnter', keyCode: 13, key: 'Enter', location: '3 (Numpad)' },
  { code: 'NumpadDecimal', keyCode: 110, key: '.', location: '3 (Numpad)' },
  { code: 'Numpad0', keyCode: 48, key: '0', location: '3 (Numpad)' },
  { code: 'Numpad1', keyCode: 49, key: '1', location: '3 (Numpad)' },
  { code: 'Numpad2', keyCode: 50, key: '2', location: '3 (Numpad)' },
  { code: 'Numpad3', keyCode: 51, key: '3', location: '3 (Numpad)' },
  { code: 'Numpad4', keyCode: 52, key: '4', location: '3 (Numpad)' },
  { code: 'Numpad5', keyCode: 53, key: '5', location: '3 (Numpad)' },
  { code: 'Numpad6', keyCode: 54, key: '6', location: '3 (Numpad)' },
  { code: 'Numpad7', keyCode: 55, key: '7', location: '3 (Numpad)' },
  { code: 'Numpad8', keyCode: 56, key: '8', location: '3 (Numpad)' },
  { code: 'Numpad9', keyCode: 57, key: '9', location: '3 (Numpad)' },
  {
    code: 'MetaLeft',
    keyCode: 91,
    key: 'Meta',
    location: '1 (Left-side modifier keys)',
  },
  { code: 'KeyC', keyCode: 67, key: 'c', location: '0 (General keys)' },

  { code: 'KeyQ', keyCode: 81, key: 'q', location: '0 (General keys)' },
  { code: 'KeyW', keyCode: 87, key: 'w', location: '0 (General keys)' },
  { code: 'KeyE', keyCode: 69, key: 'e', location: '0 (General keys)' },
  { code: 'KeyR', keyCode: 82, key: 'r', location: '0 (General keys)' },
  { code: 'KeyT', keyCode: 84, key: 't', location: '0 (General keys)' },
  { code: 'KeyY', keyCode: 89, key: 'y', location: '0 (General keys)' },
  { code: 'KeyU', keyCode: 85, key: 'u', location: '0 (General keys)' },
  { code: 'KeyI', keyCode: 73, key: 'i', location: '0 (General keys)' },
  { code: 'KeyO', keyCode: 79, key: 'o', location: '0 (General keys)' },
  { code: 'KeyP', keyCode: 80, key: 'p', location: '0 (General keys)' },
  { code: 'KeyA', keyCode: 65, key: 'a', location: '0 (General keys)' },
  { code: 'KeyS', keyCode: 83, key: 's', location: '0 (General keys)' },
  { code: 'KeyD', keyCode: 68, key: 'd', location: '0 (General keys)' },
  { code: 'KeyF', keyCode: 70, key: 'f', location: '0 (General keys)' },
  { code: 'KeyG', keyCode: 71, key: 'g', location: '0 (General keys)' },
  { code: 'KeyH', keyCode: 72, key: 'h', location: '0 (General keys)' },
  { code: 'KeyJ', keyCode: 74, key: 'j', location: '0 (General keys)' },
  { code: 'KeyK', keyCode: 75, key: 'k', location: '0 (General keys)' },
  { code: 'KeyL', keyCode: 76, key: 'l', location: '0 (General keys)' },
  { code: 'KeyZ', keyCode: 90, key: 'z', location: '0 (General keys)' },
  { code: 'KeyX', keyCode: 88, key: 'x', location: '0 (General keys)' },
  { code: 'KeyC', keyCode: 67, key: 'c', location: '0 (General keys)' },
  { code: 'KeyV', keyCode: 86, key: 'v', location: '0 (General keys)' },
  { code: 'KeyB', keyCode: 66, key: 'b', location: '0 (General keys)' },
  { code: 'KeyN', keyCode: 78, key: 'n', location: '0 (General keys)' },
  { code: 'KeyM', keyCode: 77, key: 'm', location: '0 (General keys)' },
  { code: 'Digit1', keyCode: 49, key: '1', location: '0 (General keys)' },
  { code: 'Digit2', keyCode: 50, key: '2', location: '0 (General keys)' },
  { code: 'Digit3', keyCode: 51, key: '3', location: '0 (General keys)' },
  { code: 'Digit4', keyCode: 52, key: '4', location: '0 (General keys)' },
  { code: 'Digit5', keyCode: 53, key: '5', location: '0 (General keys)' },
  { code: 'Digit6', keyCode: 54, key: '6', location: '0 (General keys)' },
  { code: 'Digit7', keyCode: 55, key: '7', location: '0 (General keys)' },
  { code: 'Digit8', keyCode: 56, key: '8', location: '0 (General keys)' },
  { code: 'Digit9', keyCode: 57, key: '9', location: '0 (General keys)' },
  { code: 'Digit0', keyCode: 48, key: '0', location: '0 (General keys)' },
  { code: 'F1', keyCode: 112, key: 'F1', location: '0 (General keys)' },
  { code: 'F2', keyCode: 113, key: 'F2', location: '0 (General keys)' },
  { code: 'F3', keyCode: 114, key: 'F3', location: '0 (General keys)' },
  { code: 'F4', keyCode: 115, key: 'F4', location: '0 (General keys)' },
  { code: 'F5', keyCode: 116, key: 'F5', location: '0 (General keys)' },
  { code: 'F6', keyCode: 117, key: 'F6', location: '0 (General keys)' },
  { code: 'F7', keyCode: 118, key: 'F7', location: '0 (General keys)' },
  { code: 'F8', keyCode: 119, key: 'F8', location: '0 (General keys)' },
  { code: 'F9', keyCode: 120, key: 'F9', location: '0 (General keys)' },
  { code: 'F10', keyCode: 121, key: 'F10', location: '0 (General keys)' },
  { code: 'F11', keyCode: 122, key: 'F11', location: '0 (General keys)' },
  { code: 'F12', keyCode: 123, key: 'F12', location: '0 (General keys)' },
  { code: 'F13', keyCode: 124, key: 'F13', location: '0 (General keys)' },
  { code: 'Escape', keyCode: 27, key: 'Escape', location: '0 (General keys)' },
  { code: 'Backquote', keyCode: 192, key: '§', location: '0 (General keys)' },
  { code: 'Tab', keyCode: 9, key: 'Tab', location: '0 (General keys)' },
  {
    code: 'ShiftLeft',
    keyCode: 16,
    key: 'Shift',
    location: '1 (Left-side modifier keys)',
  },
  {
    code: 'ControlLeft',
    keyCode: 17,
    key: 'Control',
    location: '1 (Left-side modifier keys)',
  },
  {
    code: 'MetaLeft',
    keyCode: 91,
    key: 'Meta',
    location: '1 (Left-side modifier keys)',
  },
  {
    code: 'AltLeft',
    keyCode: 18,
    key: 'Alt',
    location: '1 (Left-side modifier keys)',
  },
  {
    code: 'Space',
    keyCode: 32,
    key: '(Spacebar)',
    location: '0 (General keys)',
  },
  {
    code: 'AltRight',
    keyCode: 18,
    key: 'Alt',
    location: '2 (Right-side modifier keys)',
  },
  {
    code: 'MetaRight',
    keyCode: 93,
    key: 'Meta',
    location: '2 (Right-side modifier keys)',
  },
  {
    code: 'ContextMenu',
    keyCode: 93,
    key: 'ContextMenu',
    location: '0 (General keys)',
  },
  {
    code: 'ControlRight',
    keyCode: 17,
    key: 'Control',
    location: '2 (Right-side modifier keys)',
  },
  {
    code: 'ShiftRight',
    keyCode: 16,
    key: 'Shift',
    location: '2 (Right-side modifier keys)',
  },
  { code: 'Enter', keyCode: 13, key: 'Enter', location: '0 (General keys)' },
  {
    code: 'Backspace',
    keyCode: 8,
    key: 'Backspace',
    location: '0 (General keys)',
  },
  { code: 'Equal', keyCode: 187, key: '=', location: '0 (General keys)' },
  { code: 'Minus', keyCode: 189, key: '-', location: '0 (General keys)' },
  {
    code: 'ArrowUp',
    keyCode: 38,
    key: 'ArrowUp',
    location: '0 (General keys)',
  },
  {
    code: 'ArrowLeft',
    keyCode: 37,
    key: 'ArrowLeft',
    location: '0 (General keys)',
  },
  {
    code: 'ArrowDown',
    keyCode: 40,
    key: 'ArrowDown',
    location: '0 (General keys)',
  },
  {
    code: 'ArrowRight',
    keyCode: 39,
    key: 'ArrowRight',
    location: '0 (General keys)',
  },
  { code: 'BracketLeft', keyCode: 219, key: '[', location: '0 (General keys)' },
  {
    code: 'BracketRight',
    keyCode: 221,
    key: ']',
    location: '0 (General keys)',
  },
  { code: 'Semicolon', keyCode: 186, key: ';', location: '0 (General keys)' },
  { code: 'Quote', keyCode: 222, key: "'", location: '0 (General keys)' },
  { code: 'Backslash', keyCode: 220, key: '\\', location: '0 (General keys)' },
  { code: 'Comma', keyCode: 188, key: ',', location: '0 (General keys)' },
  { code: 'Period', keyCode: 190, key: '.', location: '0 (General keys)' },
  { code: 'Slash', keyCode: 191, key: '/', location: '0 (General keys)' },
  {
    code: 'IntlBackslash',
    keyCode: 192,
    key: '`',
    location: '0 (General keys)',
  },
];

export default keycodes;
